# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-latest'


steps:
- script: echo Run Cargo build
  displayName: 'Cargo Build'

- script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  env:
    RUSTUP_TOOLCHAIN: nightly
  displayName: "Install rust (*nix)"
  condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

- bash: |
      cd barracuda_core
      cargo build
  displayName: Run cargo build

- bash: |
      cd barracuda_core
      cargo test
      cd ..
      cd barracuda_modules
      cd generic_whitelist
      cargo test
  displayName: Run cargo test