# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  rustup_toolchain: stable      # Could be [stable, beta, nightly, 1.31, nightly-2018-08-01 ... ]
  components: []                # Rust commponents to be installed
  targets: []                   # Rust targets to be installed
  steps: []                     # Custom steps

steps:
- script: echo Run Cargo build
  displayName: 'Cargo Build'

- script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    env:
      RUSTUP_TOOLCHAIN: ${{parameters.rustup_toolchain}}
    displayName: "Install rust (*nix)"
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
  displayName: 'Install Rust'

- bash: cargo build
  displayName: Run cargo build with defined flags 