[package]
name = "target_rpi"
version = "0.1.0"
authors = ["thefux <abdou.rakez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
barracuda_core = { path = "../barracuda_core" }
rppal = "0.11.3"
