name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Core Build
      working-directory: barracuda_core
      run: cargo build --verbose
    - name: Core tests
      working-directory: barracuda_core
      run: cargo test --verbose
    - name: Whitelist Build
      working-directory: barracuda_modules/generic_whitelist
      run: cargo build --verbose
    - name: Whitelist Tests
      working-directory: barracuda_modules/generic_whitelist
      run: cargo test --verbose
    - name: MFRC522 Build
      working-directory: barracuda_modules/mfrc522
      run: cargo build --verbose
    - name: MFRC522 Tests
      working-directory: barracuda_modules/mfrc522
      run: cargo test --verbose
    - name: ADCM Tests
      working-directory: barracuda_modules/adcm
      run: cargo test --verbose
